export enum ActionTypes {
  GET_SOFTBILL_DATA = 'GET_SOFTBILL_DATA',
  UPDATE_SOFTBILL_DATA = 'UPDATE_SOFTBILL_DATA',
  GET_DEFAULT_PLANT_NUMBER = 'GET_DEFAULT_PLANT_NUMBER',
  GET_PLANT_NUMBER_LIST = 'GET_PLANT_NUMBER_LIST',
  GET_USER_DETAILS = 'GET_USER_DETAILS',
  GET_WORKORDER_DETAILS = 'GET_WORKORDER_DETAILS',
  UPDATE_PICTURE_LIST = 'UPDATE_PICTURE_LIST',
  UPDATE_SELECTED_PICTURE_LIST_ITEM = 'UPDATE_SELECTED_PICTURE_LIST_ITEM',
}
